window.KO_DICT = {
  "Skip to content": "본문 바로가기",
  "Toggle menu": "메뉴 열기/닫기",
  "Close": "닫기",

  "Home": "홈",
  "About": "소개",
  "Services": "서비스",
  "Coaching": "코칭",
  "Books": "도서",
  "Blog": "블로그",
  "Book a session": "세션 예약",
  "Process": "과정",
  "Tools": "도구",
  "Credentials": "자격",
  "Start an inquiry": "문의 시작하기",
  "Interpreting inquiry": "통역 문의",
  "Translation inquiry": "번역 문의",

  "Suzan Kim | Korean–English Interpreter & Life/Career Coach": "김수진 | 한영 통역사 & 라이프·커리어 코치",
  "Korean–English interpreter and life/career coach. Book a session, read about my translated books, and follow my blog.": "한영 통역사이자 라이프·커리어 코치입니다. 세션을 예약하고, 번역한 도서를 확인하고, 블로그를 만나보세요.",

  "Interpreter · Translator · Coach": "통역사 · 번역가 · 코치",
  "Bridging languages,": "언어를 잇고,",
  "guiding your next chapter.": "당신의 다음 장을 안내합니다.",
  "I'm a Korean–English interpreter and life & career coach. Whether you need clear communication across languages or a thoughtful partner to figure out what's next, you're in good hands.": "저는 한영 통역사이자 라이프·커리어 코치입니다. 언어를 넘어 명확하게 소통하고 싶으실 때, 혹은 다음 걸음을 함께 고민할 든든한 파트너가 필요하실 때, 믿고 맡기셔도 좋습니다.",
  "Meet me": "저를 소개합니다",
  "Portrait of Suzan Kim": "김수진 프로필 사진",

  "About me": "저를 소개합니다",
  "Hello, I'm Suzan (김수진). I grew up between Korean and English, and I've spent more than 20 years helping people understand each other, in business meetings, courtrooms, clinics, publishing, and everyday life.": "안녕하세요, 김수진입니다. 한국어와 영어 사이에서 자라, 20년 넘게 비즈니스 회의, 법정, 병원, 출판, 그리고 일상 속에서 사람들이 서로를 이해하도록 도와왔습니다.",
  "As a coach, I bring the same listening-first approach: I help people navigate career transitions, life in a new country, and big decisions with clarity and kindness.": "코치로서도 경청을 우선하는 같은 방식으로, 커리어 전환, 낯선 나라에서의 삶, 중요한 결정을 명확함과 따뜻함으로 헤쳐 나가도록 돕습니다.",
  "Languages": "언어",
  "Korean (한국어) & English": "한국어 & 영어",
  "Interpreting": "통역",
  "Medical, legal, and general documents of all kinds": "의료, 법률 및 각종 일반 문서 전반",
  "Consecutive, simultaneous, whispered, remote": "순차통역, 동시통역, 위스퍼링 통역, 원격 통역",
  "Life transitions, career growth, bilingual identity": "삶의 전환기, 커리어 성장, 이중언어 정체성",
  "CMI-Korean, KAC Certified Coach, SuccessFinder Debriefer, Birkman Debriefer/Facilitator & DTW Facilitator": "CMI-Korean, KAC 인증 코치, SuccessFinder 디브리퍼, Birkman 디브리퍼/퍼실리테이터 및 DTW 퍼실리테이터",

  "Professional Korean–English interpreting for meetings, events, medical and legal appointments, in person or online.": "회의, 행사, 의료 및 법률 상담을 위한 전문 한영 통역을 대면 또는 온라인으로 제공합니다.",
  "Send a work inquiry": "업무 문의하기",
  "Translation": "번역",
  "Korean–English translation of books, medical and legal documents, statements, and more, with care for tone and context.": "도서, 의료·법률 문서, 진술서 등을 어조와 맥락까지 세심하게 살린 한영 번역으로 제공합니다.",
  "Life Coaching": "라이프 코칭",
  "Gentle, practical sessions to help you find direction, build confidence, and make changes that stick, in Korean or English.": "방향을 찾고, 자신감을 키우고, 오래 이어지는 변화를 만들 수 있도록 돕는 따뜻하고 실질적인 세션을 한국어 또는 영어로 진행합니다.",
  "Get to know me": "저를 알아보기",
  "How coaching works": "코칭은 이렇게 진행됩니다",

  "Books I've translated": "번역한 도서",
  "A selection of Korean works brought into English.": "한국어 작품을 영어로 옮긴 선별 도서입니다.",
  "by": "저자:",
  "Kyobo": "교보문고",

  "Climate & community": "기후 & 커뮤니티",
  "Communities and practices I'm part of, bringing coaching and reflection to the climate and ecological crisis.": "기후·생태 위기에 코칭과 성찰을 접목하는, 제가 함께하고 있는 커뮤니티와 실천입니다.",
  "Climate Coaching Alliance": "기후 코칭 얼라이언스 (CCA)",
  "A global network of coaches and practitioners bringing coaching to climate and ecological challenges.": "기후와 생태 문제에 코칭을 접목하는 코치와 실천가들의 글로벌 네트워크입니다.",
  "Visit the CCA": "CCA 방문하기",
  "Deep Time Walk": "딥 타임 워크 (Deep Time Walk)",
  "A 4.6 km walk through 4.6 billion years of Earth's history, helping us experience deep time and our connection to the planet. I'm a Deep Time Walk facilitator.": "46억 년 지구의 역사를 4.6km의 걸음으로 지나며 심원한 시간(deep time)과 지구와의 연결을 체험하는 프로그램입니다. 저는 딥 타임 워크 퍼실리테이터입니다.",
  "Explore Deep Time Walk": "딥 타임 워크 둘러보기",
  "CCA Korean Community Pod": "CCA 한국어 커뮤니티 Pod",
  "The Korean-language community of the Climate Coaching Alliance, which I co-lead. Read our posts on Naver Blog.": "제가 공동 리드하고 있는 Climate Coaching Alliance의 한국어 커뮤니티입니다. 네이버 블로그에서 글을 읽어보세요.",
  "Read the Naver blog": "네이버 블로그 읽기",

  "Notes on language, culture, and finding your way.": "언어와 문화, 그리고 나만의 길을 찾는 이야기.",
  "Read more": "더 읽기",
  "What gets lost (and found) in translation": "번역에서 사라지는 것, 그리고 발견되는 것",
  "Some Korean words have no tidy English twin. Here's how I decide what to carry across.": "어떤 한국어 단어는 깔끔하게 맞는 영어 단어가 없습니다. 무엇을 옮길지 제가 어떻게 정하는지 소개합니다.",
  "Replace this with your first post.": "여기에 첫 번째 글을 입력하세요.",
  "Separate paragraphs with a blank line.": "문단은 빈 줄로 구분하세요.",
  "Starting over in a new country": "낯선 나라에서 새로 시작하기",
  "Three questions I ask every client facing a big move or career change.": "큰 이사나 커리어 전환을 앞둔 모든 분께 제가 드리는 세 가지 질문입니다.",
  "Replace this with your second post.": "여기에 두 번째 글을 입력하세요.",

  "Pick a time that suits you. You'll receive a confirmation email with the details straight away.": "편하신 시간을 선택해 주세요. 예약 즉시 세부 내용이 담긴 확인 이메일이 발송됩니다.",
  "Open the booking page in a new tab": "새 탭에서 예약 페이지 열기",

  "Suzan Kim on LinkedIn": "김수진 LinkedIn",
  "Suzan Kim": "김수진",
  "Suzan Kim. All rights reserved. ·": "김수진. 모든 권리 보유. ·",

  "Coaching | Suzan Kim": "코칭 | 김수진",
  "Bilingual Korean–English life and career coaching. Learn what coaching is, how sessions work, and start with a gentle introductory inquiry.": "한국어·영어 이중언어 라이프·커리어 코칭입니다. 코칭이란 무엇이고 세션이 어떻게 진행되는지 알아보고, 부담 없는 소개 문의로 시작해 보세요.",
  "Transformational coaching": "변화를 이끄는 코칭",
  "You deserve time": "당신의 말을 찾는 데 필요한 시간,",
  "to find your words.": "충분히 가지셔도 좋습니다.",
  "For Koreans living overseas, finding the right words can be about more than language. You may be trying to explain who you are, what matters to you, or where you want your career to go.": "해외에 사는 한국인에게 알맞은 말을 찾는 일은 단순한 언어 문제가 아닐 수 있습니다. 내가 누구인지, 무엇이 중요한지, 커리어가 어디로 향하길 원하는지를 설명하려는 일일 수 있습니다.",
  "I coach people who struggle to feel fully understood in either Korean or English. My approach gives you patience, space, and time to explain yourself as we explore your strengths and the changes you want to make.": "한국어로든 영어로든 온전히 이해받는다고 느끼기 어려운 분들을 코칭합니다. 제 방식은 인내와 공간, 그리고 스스로를 설명할 시간을 드리며, 함께 당신의 강점과 원하는 변화를 탐색합니다.",
  "Talk to me about coaching": "코칭에 대해 이야기해 보기",
  "Explore the process": "과정 살펴보기",

  "What is coaching?": "코칭이란?",
  "Coaching is a conversation that helps you understand yourself, choose goals that matter to you, and turn reflection into action. You bring your experience and hopes; I listen, ask questions, and support you as you find your own direction.": "코칭은 자신을 이해하고, 의미 있는 목표를 고르고, 성찰을 행동으로 옮기도록 돕는 대화입니다. 당신은 경험과 바람을 가져오시고, 저는 귀 기울여 듣고 질문하며 당신만의 방향을 찾도록 곁에서 지원합니다.",
  "Your voice. Your journey. Your possibilities.": "당신의 목소리. 당신의 여정. 당신의 가능성.",
  "Authenticity · Being heard · Respect · Partnership": "진정성 · 경청받는 경험 · 존중 · 파트너십",

  "How we work together": "함께 하는 방법",
  "You don't need all the answers. We start with your story, find direction together, and move forward at your pace.": "모든 답을 알 필요는 없습니다. 당신의 이야기에서 시작해 함께 방향을 찾고, 당신의 속도에 맞춰 나아갑니다.",
  "Feel heard": "이해받는 경험",
  "Space to speak. Room to be yourself.": "말할 수 있는 공간. 나다워질 수 있는 여유.",
  "Find clarity": "명확함 찾기",
  "Discover your strengths. Choose what matters.": "강점을 발견하고, 중요한 것을 선택합니다.",
  "Take action": "행동하기",
  "Try a small step. Reflect and adjust.": "작은 한 걸음을 시도하고, 돌아보며 조정합니다.",
  "Grow confidence": "자신감 키우기",
  "Trust your choices. Carry change forward.": "자신의 선택을 믿고, 변화를 앞으로 이어갑니다.",

  "Your coaching journey": "코칭 여정",
  "One step at a time, with support.": "한 걸음씩, 곁에서 함께합니다.",
  "Getting to know you": "서로 알아가기",
  "We begin with an introductory conversation about your situation, hopes, and what you need to feel comfortable. There is time to find your words and see whether we are a good fit.": "당신의 상황과 바람, 편안함을 느끼기 위해 필요한 것에 대한 소개 대화로 시작합니다. 말을 찾을 시간이 충분히 있으며, 우리가 서로 잘 맞는지도 함께 살펴봅니다.",
  "Agreeing on our partnership": "파트너십 합의하기",
  "Before sessions begin, we review and sign a coaching agreement covering goals, expectations, practical arrangements, and confidentiality. You can ask questions before deciding to proceed.": "세션을 시작하기 전에 목표, 기대, 실무적인 사항, 비밀 보장을 다루는 코칭 계약서를 함께 검토하고 서명합니다. 진행 여부를 결정하기 전에 언제든 질문하실 수 있습니다.",
  "Beginning your sessions": "세션 시작하기",
  "We explore your strengths, experiences, and priorities. Together, we shape goals and manageable next steps that fit your life and your pace.": "당신의 강점, 경험, 우선순위를 탐색합니다. 그리고 당신의 삶과 속도에 맞는 목표와 실행 가능한 다음 단계를 함께 만들어 갑니다.",
  "Checking progress and adjusting": "진행 상황 점검과 조정",
  "We regularly reflect on what is changing, what is helping, and what feels difficult. We evaluate progress together and adjust your goals or plan when needed.": "무엇이 바뀌고 있는지, 무엇이 도움이 되는지, 무엇이 어려운지 정기적으로 돌아봅니다. 진행 상황을 함께 평가하고 필요하면 목표나 계획을 조정합니다.",
  "Carrying your growth forward": "성장을 이어가기",
  "As we bring our work to a close, we reflect on what you have learned and plan how to keep using it. The aim is greater self-reliance and changes you can keep building on in everyday life.": "코칭을 마무리하며 배운 것을 돌아보고 앞으로 어떻게 활용할지 계획합니다. 목표는 더 큰 자립심과, 일상에서 계속 쌓아갈 수 있는 변화입니다.",
  "Encouragement throughout": "늘 곁에서 응원합니다",
  "In every session you have a supportive space to share feelings and challenges. We work on action planning, putting ideas into practice, and noticing what you learn along the way. You choose the actions; I help you reflect, stay encouraged, and find a workable next step.": "모든 세션에서 감정과 어려움을 나눌 수 있는 지지적인 공간이 마련됩니다. 실행 계획을 세우고, 아이디어를 실천하며, 그 과정에서 배우는 것을 알아차리는 작업을 함께 합니다. 행동은 당신이 선택하고, 저는 돌아보고, 힘을 내고, 실행 가능한 다음 단계를 찾도록 돕습니다.",
  "When helpful, we use SMART goals: Specific, Measurable, Achievable, Relevant, and Time-bound.": "도움이 될 때는 SMART 목표(구체적, 측정 가능, 달성 가능, 관련성, 기한 설정)를 활용합니다.",
  "Your story deserves care and privacy": "당신의 이야기는 존중과 사생활 보호를 받을 자격이 있습니다",
  "I treat what you share with care and respect. Before we begin, we discuss how your information is handled and the boundaries of confidentiality, including any legal or safety-related exceptions. You can ask questions and share at a pace that feels comfortable.": "당신이 나누는 이야기는 조심스럽고 존중하는 마음으로 다룹니다. 시작하기 전에 정보가 어떻게 처리되는지, 법적 또는 안전과 관련된 예외를 포함한 비밀 보장의 범위에 대해 이야기 나눕니다. 편안한 속도로 질문하고 이야기하셔도 됩니다.",

  "Tools for self-understanding": "자기 이해를 위한 도구",
  "Different lenses, your own story. I use SuccessFinder, the Birkman Method, and the Enneagram to support strengths and career exploration. We choose together which fits your goals.": "서로 다른 렌즈로, 당신만의 이야기를 바라봅니다. 강점과 커리어 탐색을 돕기 위해 SuccessFinder, Birkman Method, 에니어그램을 활용하며, 어떤 도구가 목표에 맞는지 함께 선택합니다.",
  "A behavioral assessment that explores workplace traits and competencies. We use the profile to discuss your strengths, development areas, and possible career directions.": "직장에서의 행동 특성과 역량을 살펴보는 행동 진단입니다. 이 프로파일을 바탕으로 강점, 발전 영역, 가능한 커리어 방향을 이야기합니다.",
  "Explore SuccessFinder": "SuccessFinder 둘러보기",
  "The Birkman Method": "Birkman Method",
  "An assessment of interests, usual behavior, underlying needs, and how behavior can change under stress. We explore which environments support you and what the patterns mean for communication and career choices.": "관심사, 평소의 행동, 내면의 욕구, 그리고 스트레스 상황에서 행동이 어떻게 달라지는지를 살펴보는 진단입니다. 어떤 환경이 당신에게 도움이 되는지, 그 패턴이 소통과 커리어 선택에 어떤 의미인지 탐색합니다.",
  "Explore the Birkman Method": "Birkman Method 둘러보기",
  "Enneagram": "에니어그램",
  "A framework of nine personality types for exploring recurring motivations and patterns. We use it as a reflective conversation about what drives you and where you want to grow.": "반복되는 동기와 패턴을 탐색하는 아홉 가지 성격 유형의 틀입니다. 무엇이 당신을 움직이는지, 어디에서 성장하고 싶은지에 대한 성찰적 대화로 활용합니다.",
  "Explore the Enneagram": "에니어그램 둘러보기",
  "These tools inform our conversation; they do not define you or determine your career. Your lived experience, priorities, and choices remain central.": "이 도구들은 우리의 대화에 참고가 될 뿐, 당신을 규정하거나 커리어를 결정하지 않습니다. 당신이 살아온 경험과 우선순위, 선택이 언제나 중심입니다.",

  "Education & specialities": "학력 & 전문 분야",
  "KAC Certified Coach (Korea Coach Association)": "KAC 인증 코치 (한국코치협회)",
  "Assessments": "진단 도구",
  "SuccessFinder Debriefer; Birkman Debriefer & Facilitator": "SuccessFinder 디브리퍼; Birkman 디브리퍼 & 퍼실리테이터",
  "Facilitation": "퍼실리테이션",
  "Deep Time Walk (DTW) Facilitator": "딥 타임 워크(DTW) 퍼실리테이터",
  "Climate": "기후",
  "Co-lead, Korean-language community pod, Climate Coaching Alliance": "Climate Coaching Alliance 한국어 커뮤니티 Pod 공동 리드",
  "Medical, legal, and general document translation, with accuracy, confidentiality, and attention to context": "의료, 법률 및 각종 일반 문서 번역 — 정확성과 비밀 보장, 맥락에 대한 세심한 배려를 바탕으로 합니다",
  "Certified Medical Interpreter (CMI-Korean); legal, IT, and business settings": "공인 의료통역사(CMI-Korean); 법률, IT, 비즈니스 분야",
  "Specialities": "전문 분야",
  "Life transitions, career growth, working across cultures, bilingual identity": "삶의 전환기, 커리어 성장, 문화 간 협업, 이중언어 정체성",

  "A little start, before we talk": "대화에 앞서 가볍게 시작해 보세요",
  "Where would you like to begin?": "어디에서 시작하고 싶으신가요?",
  "You don't need to have it all figured out. These questions are a gentle invitation to prepare for our first conversation. Only your name and email are required; share as much or as little as feels comfortable.": "모든 것이 정리되어 있을 필요는 없습니다. 이 질문들은 첫 대화를 준비하도록 돕는 부드러운 초대입니다. 이름과 이메일만 필수이며, 편안한 만큼만 나누셔도 됩니다.",
  "Preferred name *": "선호하는 이름 *",
  "Email *": "이메일 *",
  "1. What would you like to be different in your life right now? (optional)": "1. 지금 삶에서 무엇이 달라지길 바라시나요? (선택)",
  "2. Is there a challenge or topic you'd like us to explore together? (optional)": "2. 함께 탐색하고 싶은 어려움이나 주제가 있나요? (선택)",
  "3. What would help you feel supported or make our first conversation worthwhile? (optional)": "3. 어떤 점이 있으면 지지받는다고 느끼거나 첫 대화가 의미 있다고 느끼실까요? (선택)",
  "Preferred dates or times (optional)": "희망하는 날짜 또는 시간 (선택)",
  "e.g. Saturday mornings": "예: 토요일 오전",
  "City or timezone (optional)": "도시 또는 시간대 (선택)",
  "I value confidentiality. A brief outline is enough here; you can save sensitive personal details for our conversation.": "비밀 보장을 소중히 여깁니다. 여기에는 간략한 개요만 적으셔도 충분하며, 민감한 개인 정보는 대화에서 나누셔도 됩니다.",
  "Prepare my inquiry": "문의 내용 준비하기",
  "Your email draft": "이메일 초안",
  "Open in my email app": "내 이메일 앱에서 열기",
  "Copy inquiry": "문의 내용 복사",
  "This prepares an email for you to send; nothing is sent automatically. I aim to reply within 48 hours. Preferred times are not confirmed bookings. If your email app doesn't open, copy the text into an email to": "이메일 초안을 준비해 드릴 뿐 자동으로 발송되지는 않습니다. 48시간 이내에 답변드리는 것을 목표로 합니다. 희망 시간은 확정된 예약이 아닙니다. 이메일 앱이 열리지 않으면 내용을 복사해 다음 주소로 보내 주세요:",
  ".": "",

  "Interpreting inquiry | Suzan Kim": "통역 문의 | 김수진",
  "Request Korean–English interpreting. Share a few details and I'll reply by email with availability and a quote.": "한영 통역을 요청하세요. 몇 가지 정보를 알려주시면 가능 일정과 견적을 이메일로 답변드립니다.",
  "Tell me about your assignment.": "의뢰 내용을 알려주세요.",
  "Share a few details so I can review availability, preparation needs, and a quote. I aim to respond by email within 48 hours.": "가능 일정, 준비 사항, 견적을 검토할 수 있도록 몇 가지 정보를 알려주세요. 48시간 이내에 이메일로 답변드리는 것을 목표로 합니다.",
  "An inquiry does not confirm a booking. For urgent requests, choose \"Rush\" and include your required timing.": "문의가 곧 예약 확정을 의미하지는 않습니다. 긴급한 요청은 \"긴급\"을 선택하고 필요한 일정을 함께 적어 주세요.",

  "Your contact details": "연락처 정보",
  "Your name *": "성함 *",
  "Organization / agency": "소속 기관 / 에이전시",
  "Phone (optional)": "전화번호 (선택)",
  "Is this a rush request? *": "긴급 요청인가요? *",
  "No — standard timing": "아니요 — 일반 일정",
  "Yes — rush request": "예 — 긴급 요청",
  "Language direction *": "언어 방향 *",
  "Both directions (English ↔ Korean)": "양방향 (영어 ↔ 한국어)",
  "English → Korean": "영어 → 한국어",
  "Korean → English": "한국어 → 영어",
  "Other — describe below": "기타 — 아래에 설명해 주세요",

  "Interpreting assignment": "통역 의뢰 내용",
  "Assignment date *": "일자 *",
  "Start time *": "시작 시간 *",
  "Assignment time zone *": "시간대 *",
  "e.g. Asia/Seoul": "예: Asia/Seoul",
  "Expected duration (hours) *": "예상 소요 시간 (시간) *",
  "Category *": "분야 *",
  "Medical": "의료",
  "Legal": "법률",
  "Community": "커뮤니티",
  "Business": "비즈니스",
  "Other": "기타",
  "Delivery mode *": "진행 방식 *",
  "In person": "대면",
  "VRI — video remote interpreting": "VRI — 화상 원격 통역",
  "OPI — over-the-phone interpreting": "OPI — 전화 통역",
  "Zoom / online meeting": "Zoom / 온라인 회의",
  "Other / not sure": "기타 / 잘 모르겠음",
  "Interpreting style *": "통역 방식 *",
  "Consecutive — speakers take turns": "순차통역 — 화자가 번갈아 말함",
  "Simultaneous — interpreting while the speaker talks": "동시통역 — 화자가 말하는 동안 통역",
  "Not sure — please advise": "잘 모르겠음 — 안내 부탁드립니다",
  "Venue / city or online platform": "장소 / 도시 또는 온라인 플랫폼",
  "Approximate number of participants": "대략적인 참석 인원",
  "Required credentials / court authorization (if any)": "요구되는 자격 / 법원 인가 (해당 시)",
  "Assignment details: setting, topics, participants, preparation needs *": "의뢰 상세 내용: 상황, 주제, 참석자, 준비 사항 *",
  "For legal work, specify discovery, a deposition, a court hearing, a lawyer consultation, or another setting. For medical work, describe the appointment type or specialty without patient identifiers. Include any equipment or recording requirements.": "법률 업무의 경우 증거개시(디스커버리), 증언 녹취, 법정 심리, 변호사 상담 등 해당 상황을 적어 주세요. 의료 업무의 경우 환자 식별 정보 없이 진료 유형이나 전문 분야를 적어 주세요. 장비 또는 녹음 요건이 있으면 함께 알려주세요.",
  "Confidentiality starts with your inquiry.": "비밀 보장은 문의 단계부터 시작됩니다.",
  "Please send a general description first, without patient names, identification numbers, or detailed private case information. We can agree on a secure way to share documents and preparation materials after the initial conversation.": "환자 이름, 식별 번호, 상세한 개인 사건 정보 없이 먼저 일반적인 설명만 보내 주세요. 문서와 준비 자료를 공유하는 안전한 방법은 첫 대화 후에 함께 정하겠습니다.",
  "This form prepares an email to": "이 양식은 다음 주소로 보낼 이메일을 준비합니다:",
  "Please send a general description first, without patient names, identification numbers, or detailed private case information. We can agree on a secure way to share documents after the initial conversation.": "환자 이름, 식별 번호, 상세한 개인 사건 정보 없이 먼저 일반적인 설명만 보내 주세요. 문서를 공유하는 안전한 방법은 첫 대화 후에 함께 정하겠습니다.",  ". Your email app will open; please review the message and press Send there. Nothing is sent until you do.": ". 이메일 앱이 열리면 내용을 확인하고 그곳에서 보내기를 눌러 주세요. 직접 보내기 전까지는 아무것도 전송되지 않습니다.",
  "Prepare my inquiry email": "문의 이메일 준비하기",
  "Your inquiry: review or copy": "문의 내용: 확인 또는 복사",
  "If your email app doesn't open, copy the text into an email to": "이메일 앱이 열리지 않으면 내용을 복사해 다음 주소로 이메일을 보내 주세요:",

  "Translation inquiry | Suzan Kim": "번역 문의 | 김수진",
  "Request Korean–English translation. Share a few details and I'll reply by email with timing and a quote.": "한영 번역을 요청하세요. 몇 가지 정보를 알려주시면 소요 일정과 견적을 이메일로 답변드립니다.",
  "Tell me about your project.": "프로젝트에 대해 알려주세요.",
  "Share a few details so I can review timing, preparation needs, and a quote. I aim to respond by email within 48 hours.": "소요 일정, 준비 사항, 견적을 검토할 수 있도록 몇 가지 정보를 알려주세요. 48시간 이내에 이메일로 답변드리는 것을 목표로 합니다.",
  "An inquiry does not confirm a booking or deadline. For urgent requests, choose \"Rush\" and include your required timing.": "문의가 곧 예약이나 마감일 확정을 의미하지는 않습니다. 긴급한 요청은 \"긴급\"을 선택하고 필요한 일정을 함께 적어 주세요.",
  "Translation project": "번역 프로젝트",
  "Project type *": "프로젝트 유형 *",
  "Book": "도서",
  "Medical records / charts": "의무 기록 / 차트",
  "Legal documents": "법률 문서",
  "Statements": "진술서",
  "Machine translation post-editing": "기계 번역 후편집",
  "Video / audio transcription": "영상 / 음성 전사",
  "Game translation / localization": "게임 번역 / 현지화",
  "Certification / notarization requirements": "인증 / 공증 요건",
  "Not required": "필요 없음",
  "Certified translation requested": "인증 번역 요청",
  "Notarization requested": "공증 요청",
  "Required deadline (date & time) *": "희망 마감일 (날짜 및 시간) *",
  "Deadline time zone *": "마감 시간대 *",
  "Approximate words, pages, or recording minutes": "대략적인 단어 수, 페이지 수 또는 녹음 분량(분)",
  "Source & desired delivery formats": "원본 및 희망 납품 형식",
  "e.g. PDF in, Word out": "예: PDF로 받아 Word로 납품",
  "Project details: purpose, audience, subject, special instructions *": "프로젝트 상세 내용: 목적, 독자, 주제, 특이 사항 *",

  "Copied": "복사됨",
  "Select the text above to copy": "위 텍스트를 선택해 복사하세요",
  "Please add your name and a valid email address.": "이름과 올바른 이메일 주소를 입력해 주세요.",
  "Please fill in the required fields marked with *.": "* 표시된 필수 항목을 모두 입력해 주세요.",
  "To:": "받는 사람:",
  "Subject:": "제목:",
  "Hello Suzan,": "안녕하세요, 김수진 님.",
  "Thank you,": "감사합니다.",
  "I'd like to make an interpreting inquiry.": "통역 문의를 드립니다.",
  "I'd like to make a translation inquiry.": "번역 문의를 드립니다.",
  "I'd like to talk about coaching.": "코칭에 대해 이야기 나누고 싶습니다.",
  "Name:": "이름:",
  "Email:": "이메일:",
  "What I'd like to be different:": "달라지길 바라는 점:",
  "Challenge or topic to explore:": "탐색하고 싶은 어려움 또는 주제:",
  "What would help me feel supported:": "지지받는다고 느끼는 데 도움이 될 점:",
  "Preferred dates or times:": "희망 날짜 또는 시간:",
  "City or timezone:": "도시 또는 시간대:",
  "Coaching inquiry": "코칭 문의"
};
